name: music_player
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  file_selector: 1.0.0
  file_selector_windows: 0.9.3+4
  file_picker: ^5.3.0
  audio_metadata_reader: ^1.4.2  # 用于读取音频元数据
  path: ^1.8.3           # 处理文件路径
  path_provider: ^2.0.15 # 用于获取临时目录
  shared_preferences: ^2.2.2  # 新增，用于保存设置和音频信息

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  fonts:
    - family: MiSans
      fonts:
        - asset: fonts/MiSans-Regular.ttf
  uses-material-design: true
